name: google_maps_place_picker_mb
description: A Flutter plugin which provides 'Picking Place' using Google Maps
  widget. (MB version)
version: 3.2.1
homepage: https://github.com/martin-braun-net/google_maps_place_picker_mb

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator_android: ^5.0.0
  geolocator_apple: ^2.3.8
  geolocator_platform_interface: ^4.2.3
  geolocator_web: ^4.1.1
  geolocator_windows: ^0.2.3
  google_api_headers: ">=4.0.3 <6.0.0"
  google_maps_flutter: ^2.6.1
  flutter_google_maps_webservices: ^1.1.1
  http: ^1.1.0
  provider: ^6.0.5
  tuple: ^2.0.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


false_secrets:
  - /example/lib/keys.dart
  - /example/android/app/src/main/AndroidManifest.xml
  - /example/ios/Runner/AppDelegate.swift
